- alias: 'thema'
  trigger:
    - platform: time_pattern
      minutes: '/5'
  action:
    - service_template: frontend.set_theme
      data_template:
      name: >
        {% if states.sun.sun.state == "above_horizon" %}
          Light - Orange
        {% else %}
          Dark - Orange
        {% endif %}
