homeassistant: !include Statisch/homeassistant.yaml
device_tracker: !include Statisch/device_tracker.yaml
media_player: !include Statisch/media_players.yaml
cast: !include Statisch/cast.yaml
http: !include Statisch/http.yaml
cloud: !include Statisch/google.yaml
frontend: !include Statisch/frontend.yaml
mqtt: !include Statisch/mqtt.yaml
binary_sensor: !include_dir_list Binaire Sensor
input_number: !include Input/input_number.yaml
automation: !include_dir_list Automatiseringen
script: !include_dir_merge_named Scripts
sensor: !include sensors.yaml
group: !include groups.yaml
switch: !include switches.yaml
light: !include lights.yaml
scene: !include_dir_list Scenes
notify: 
  - platform: webostv
    host: 10.10.10.99
    name: LG
    filename: webostv.conf
config:
history:
recorder:
logbook:
logger:
  default: error
  logs:
    homeassistant.components.mqtt: debug