
- platform: mqtt
  name: "Deurbel"
  state_topic: "stat/deurbel/POWER1"
  command_topic: "cmnd/deurbel/POWER1"
  availability_topic: "tele/deurbel/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  
- platform: mqtt
  name: "Deurbel Sensor"
  state_topic: "stat/deurbel/POWER2"
  command_topic: "cmnd/deurbel/POWER2"
  availability_topic: "tele/deurbel/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  
- platform: mqtt
  name: "Multimedia"
  state_topic: "stat/multimedia/POWER"
  command_topic: "cmnd/multimedia/POWER"
  availability_topic: "tele/multimedia/LWT"
  qos: 1
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  retain: true
  

- platform: broadlink
  host: 10.10.10.31
  mac: '78:0F:77:52:00:AF'
  timeout: 15
  friendly_name: 'RF Woonkamer'
  switches:
    stereo_harder:
      friendly_name: 'Home-Cinema Volume +'
      command_on: 'JgCQAAABGYwSERI0EjQSERIREjQSERI0EjQSERISEjMTMxISEjQSERIREjQSERI0EhESERMREhESNBIREjQSERI0EjQSNBIxFgADQwABGosTEBMzEjQSERIREzMTERI0EzITERIREjQSNBIREjQSERIREjQSERMzExESERIREhESNBIREzMSEhIzEzMTMxI0EgANBQAAAAAAAAAA=='
      command_off: 'JgCQAAABGYwSERI0EjQSERIREjQSERI0EjQSERISEjMTMxISEjQSERIREjQSERI0EhESERMREhESNBIREjQSERI0EjQSNBIxFgADQwABGosTEBMzEjQSERIREzMTERI0EzITERIREjQSNBIREjQSERIREjQSERMzExESERIREhESNBIREzMSEhIzEzMTMxI0EgANBQAAAAAAAAAA=='
    stereo_zachter:
      friendly_name: 'Home-Cinema Volume -'
      command_on: 'JgDYAAABGYsTERIzEzMSEhIREzMTEBI0EzMSERIREjQTMxMQEjQTERE0EjQTEBMzExESERIREhETEBISEjQSERMzEjQSNBIzEwADRAABGYsSERI0EzMSERQQEzMSERMzEjQSERIREzMTMxMQEzMTDRU0EjQSERMzExATERMQExAUDxIREzMSEhMyEjQSNBI0EwADQwABGosSERMzEjQSERISETQSERI0EzMSERMREjQSMxISEzMSEhE0EjQSEBM0ExASERIREhITEBISETQTERE0EzMTMxMzEgANBQ=='
      command_off: 'JgDYAAABGYsTERIzEzMSEhIREzMTEBI0EzMSERIREjQTMxMQEjQTERE0EjQTEBMzExESERIREhETEBISEjQSERMzEjQSNBIzEwADRAABGYsSERI0EzMSERQQEzMSERMzEjQSERIREzMTMxMQEzMTDRU0EjQSERMzExATERMQExAUDxIREzMSEhMyEjQSNBI0EwADQwABGosSERMzEjQSERISETQSERI0EzMSERMREjQSMxISEzMSEhE0EjQSEBM0ExASERIREhITEBISETQTERE0EzMTMxMzEgANBQ=='
    setopbox_1:
      friendly_name: 'Setopbox 1'
      command_on: 'JgBiAFYdDw4PDg8cDxwsDg4PDh0ODx4NDxwPDg8ODg8ODw4PHB0PDg4PDg8dDg8cHhwcAAjrVxwPDg8ODxwPHCwODw4OHQ8OHg0PHBANDw4ODw4PDg8dHA8OHR0dDg4dHRwdAA0FAAAAAAAA='
    setopbox_2:
      friendly_name: 'Setopbox 2'
      command_on: 'JgBmAFccDw4PDg8cDxwsDg8ODh0PDh0ODxwPDg8ODw4ODw4PHRwPDg4PDg8dHB0PEAwPHQ4ACN1WHQ8ODg8OHQ4dKw8ODw4dDw4dDg4dDw4ODw4PDg4PDh0dDw4dHB0dHQ4ODw4dDwANBQAA='
    setopbox_3:
      friendly_name: 'Setopbox 3'
      command_on: 'JgBmAFYdDw4PDg4dDh0rDw8ODh0ODxwPDh0PDg4PDw4ODw4OHR0ODw4PDg4dHQ8OHQ4PDg8ACOpXHQ8ODg4QHA4dKw4PDg8cEA0dDg8dDg8ODhANDw4PDh0dDg4dHR0cEA0dDw8NDwANBQAA='
    setopbox_4:
      friendly_name: 'Setopbox 4'
      command_on: 'JgBmAFYdDw4ODw4dDxwrDw4PDh0ODx0ODh0ODw4PDg8PDg4OHR0ODw4PDg8PDR4cDw4dDg4ACOtXHQ8ODw0PHQ4dKw4PDhAbDw4dDg8dDg8ODg8ODw4PDh0cDw4dHQ8OHRwPDh0OEAANBQAA='
    setopbox_5:
      friendly_name: 'Setopbox 5'
      command_on: 'JgBmAFcdDw4ODw4dDh0rDw4PDh0ODxwPDxwPDg8ODg8ODg8OHhwPDg8ODg4PDh0ODx0dHA8ACNxXHQ8ODw4OHQ8cKw8ODg8dDg4dDw4dDw4ODw4OEA0PDh0dDg8cHQ8OHgsRHB0dDgANBQAA='
    setopbox_6:
      friendly_name: 'Setopbox 6'
      command_on: 'JgBqAFcdDw0QDRAbEBwrDg8OEBsQDR4NEBwPDRANEA0PDg4PHRwQDQ8OEA0PDg4PHQ4PHA8ODwAI3FcdDw4PDQ8dDh0rDhANDxwPDh0PDh0PDg4ODw4PDhANHR0ODh0dDg8PDh0ODxwPDg4ADQUAAAAAAAAAAAAAAAAAAA=='
    setopbox_7:
      friendly_name: 'Setopbox 7'
      command_on: 'JgBmAFYdEA0QDQ8cEBssDg8ODxwQDR4NDxwPDg8ODw4ODw8OHRwQDQ8ODw4dDg8cHQ4PHQ8ACNxWHQ8ODw4PHA8cLA4ODw4dDw4dDQ8dDw4PDg4PDg8ODxwdDw4eGx0MEhwdDg8cDwANBQAA='
    setopbox_8:
      friendly_name: 'Setopbox 8'
      command_on: 'JgBmAFYdDw4PDg4dDxwrDw8ODh0ODx0ODh0PDg4PDg8ODw4OHR0ODw4PDg8dHB0ODw4QDQ8ACOpXHQ8ODw0PHQ4dKw4PDg8cDw4dDhAcDg8ODg8NEA4PDh0dDg4dHR0cHQ8PDg4ODwANBQAA='
    setopbox_9:
      friendly_name: 'Setopbox 9'
      command_on: 'JgBmAFgcDw4ODw4dDxwrDw8ODh0PDhwPDh0PDg4PDw4PDRANHhwPDg4PDg4dHR0cEA0PDg8ACNxXHQ8ODw4PHA4dKw4PDhAcDw0dDw4dDg8ODw8NDw4PDh0dDg8cHR0dHRwPDg8ODgANBQAA='
    setopbox_0:
      friendly_name: 'Setopbox 0'
      command_on: 'JgBmAFYdDw4ODw4dDh0rDw4PDh0PDh0ODh0PDg8ODg8ODw4OHR0ODw4PDg8PDR0PDh0dDg4ACOtXHQ8NEA0PHA8dKw4PDg8cDw4dDg8dDg4PDg8ODw4ODx0cEA0eHA8OHQ4OHR0ODwANBQAA='
    hdmiswitch_1:
      friendly_name: 'HDMI Switch 1'
      command_on: 'JgBQAAABLpIVEBYQFRAVEBYPFhAVEBYQFTQWNBY0FTUVNBY0FjQWNBU0FhAVNBYQFg8WEBUQFg8WEBU0FhAWNBU0FjQWNBY0FQAFHQABLkcWAA0FAAAAAAAAAAA='
    hdmiswitch_2:
      friendly_name: 'HDMI Switch 2'
      command_on: 'JgBYAAABLpIVEBYPFhAVEBYPFhAVEBYPFjQWNBY0FTQWNBY0FjQVNBYQFRAWDxY0Fg8WEBUQFg8WNBY0FjQVEBY0FTQWNBY0FgAFGwABLkcWAAxVAAEtRxYADQU='
    hdmiswitch_3:
      friendly_name: 'HDMI Switch 3'
      command_on: 'JgBcAAABLZMUERURFRAUEhMSFBEUEhMSEzcUNRU1EzcUNhM2FTUUNhQRFDYUEhQ1FBIUERQRFBIUNRURFDYUERM3EzcUNRQ2FAAFHgABLUgUAAsYBwABOgABLEkTAA0FAAAAAAAAAAAAAAAA'

   
   
   
   
   
   
   
   
   
   
