alias: 'HDMI Switch' 
initial_state: 'on'
hide_entity: true
trigger:
  platform: state
  entity_id: input_select.hdmi_switch
action:
  service: homeassistant.turn_on
  data_template:
    entity_id: >
     {% if is_state('input_select.hdmi_switch', 'TV') %}
     script.hdmiswitch_1
     {% elif is_state('input_select.hdmi_switch', 'Chromecast') %}
     script.hdmiswitch_2
     {% elif is_state('input_select.hdmi_switch', 'Playstation 4') %}
     script.hdmiswitch_3
     {% endif %}

