alias: 'RF - TV Kanalen' 
initial_state: 'off'
hide_entity: true
trigger:
  platform: state
  entity_id: input_select.tv_kanalen
action:
  service: homeassistant.turn_on
  data_template:
    entity_id: >
     {% if is_state('input_select.tv_kanalen', '(1) NPO 1') %}
     script.npo1
     {% elif is_state('input_select.tv_kanalen', '(2) NPO 2') %}
     script.npo2
     {% elif is_state('input_select.tv_kanalen', '(3) Nederland 3') %}
     script.ned3
     {% elif is_state('input_select.tv_kanalen', '(4) RTL 4') %}
     script.rtl4
     {% elif is_state('input_select.tv_kanalen', '(5) RTL 5') %}
     script.rtl5
     {% elif is_state('input_select.tv_kanalen', '(6) SBS 6') %}
     script.sbs6
     {% elif is_state('input_select.tv_kanalen', '(7) RTL 7') %}
     script.rtl7
     {% elif is_state('input_select.tv_kanalen', '(8) Veronica / Disney XD') %}
     script.veronica_disneyxd
     {% elif is_state('input_select.tv_kanalen', '(9) Net 5') %}
     script.net5
     {% elif is_state('input_select.tv_kanalen', '(10) RTL8') %}
     script.rtl8
     {% elif is_state('input_select.tv_kanalen', '(11) RTL Z') %}
     script.rtlz
     {% elif is_state('input_select.tv_kanalen', '(12) SBS 9') %}
     script.sbs9
     {% elif is_state('input_select.tv_kanalen', '(13) FOX') %}
     script.fox
     {% elif is_state('input_select.tv_kanalen', '(14) Comedy Central') %}
     script.comedy_central
     {% elif is_state('input_select.tv_kanalen', '(15) FOX Sports 1') %}
     script.foxsport1
     {% elif is_state('input_select.tv_kanalen', '(16) Disney Channel') %}
     script.disney_channel
     {% elif is_state('input_select.tv_kanalen', '(17) TLC') %}
     script.tlc
     {% elif is_state('input_select.tv_kanalen', '(18) Zender van de Maand') %}
     script.zender_vd_maand
     {% elif is_state('input_select.tv_kanalen', '(19) Spike') %}
     script.spike
     {% elif is_state('input_select.tv_kanalen', '(21) Een') %}
     script.een
     {% elif is_state('input_select.tv_kanalen', '(22) Canvas') %}
     script.canvas
     {% elif is_state('input_select.tv_kanalen', '(23) Ketnet') %}
     script.ketnet
     {% elif is_state('input_select.tv_kanalen', '(24) 24 Kitchen') %}
     script.24kitchen
     {% elif is_state('input_select.tv_kanalen', '(26) Viceland') %}
     script.viceland
     {% elif is_state('input_select.tv_kanalen', '(61) Discovery Channel') %}
     script.discovery
     {% elif is_state('input_select.tv_kanalen', '(65) ID Channel') %}
     script.id

     {% endif %}

