alias: Bedtijd
trigger:
- platform: state
  entity_id: 
  - group.woonkamer
  from: "on"
  to: "off"
condition:
  condition: time
  after: "21:00:00"
  before: "23:45:00"
action:
- service: light.turn_on
  entity_id: light.lamp_slaapkamer
