alias: 'Jayden - Avond Led'
trigger:
  platform: time
  at: '19:00:00'
condition:
  condition: time
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
action:
  service: light.turn_on
  entity_id: light.jayden_led
