alias: "Jeffrey - Thuiskomst Licht"
trigger:
  platform: state
  entity_id: device_tracker.huawei_p205d2e2474c3d0ec
  to: "home"
condition:
  condition: state
  entity_id: binary_sensor.lux_laag
  state: "on"
action:
  service: light.turn_on
  entity_id: 
    - light.salontafel
    - light.eettafel
    - light.binnenkomst_lamp
