alias: "Jeffrey - Thuiskomst TV (Aan)"
trigger:
  platform: state
  entity_id: device_tracker.huawei_p205d2e2474c3d0ec
  to: "home"
condition:
  - condition: state
    entity_id: switch.tv_aan_uit
    state: 'on'
action:
  - service: switch.turn_on
    entity_id: 
      - switch.setopbox_6
  - service: switch.turn_on
    entity_id: 
      - switch.setopbox_1